# -*- coding: utf-8 -*-
"""add_adjacent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PpL6zHO9lztUC6xNwynzMHhJmB9Juhbn
"""

nums = [1,11,2,22,3,33,4,44,5,55,]
every_first_element = nums[0::2]
every_second_element = nums[1::2]
# print(every_first_element)
# print(every_second_element)

zipper = list(zip(every_first_element, every_second_element))
# print(zipper)

# for k, v in enumerate(nums):
    # print(k)
    # print(k+1)

for i in range(len(nums)-1):
    x_list = []
    y_list = []
    x = nums[i]
    x_list.append(x)
    y = nums[i+1]
    y_list.append(y)
    # print (x,y, x + y)
    print(x_list)
    xy_list = zip(x_list, y_list)
    # print(list(xy_list))

nums = [1,11,2,22,3,33,4,44,5,55]

x_list = []
y_list = []
summed_list = []
for i in range(len(nums)-1):
    summed = nums[i] + nums[i+1]
    x_list.append(nums[i])
    y_list.append(nums[i+1])
    summed_list.append(summed)
print(summed_list)
print(x_list, y_list)



