# -*- coding: utf-8 -*-
"""fib_gen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wr1Qebk8-yTxo0755_ngUr3AdYbW4qAa

fib yield
"""

def fibbi_yield(num_of_loops):
    a = 0
    b = 1
    for x in range(num_of_loops):
        yield a # 0
        temp = a # 0
        a = b # 1
        b = temp + b # 0 + 1


for x in fibbi_yield(100):
    print(x)

"""fib list"""

def fibbi_list(num_of_loops):
    a = 0
    b = 1
    result = []
    for x in range(num_of_loops):
        result.append(a)
        temp = a # 0
        a = b # 1
        b = temp + b # 0 + 1
    return result


fibbi_list(100)