# -*- coding: utf-8 -*-
"""filter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sYMMKJrfiB8vFU9iyKdfNFVOlrOxUhgt
"""

# filter()



def return_odd_numbers(numbs):
    odd = []
    for n in numbs:
        n = n % 2 != 0
        odd.append(n)

    return odd

def return_odd_numbers_filter(nums):
    return nums % 2 != 0

print(return_odd_numbers([1,2,3,4,5,6,7,8,9,10]))
print(list(filter(return_odd_numbers_filter, [1,2,3,4,5,6,7,8,9,10])))