# -*- coding: utf-8 -*-
"""lambda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xFHK4RNh3STMczgADdCkryVnn9BMdt7D

lambda()
"""

lst = [1,2,3,4,5]

lam = list(map(lambda item: item+1, lst))
print(lam)

"""square"""

lst = [1,2,3,4,5]

lam = list(map(lambda item: item * item, lst))
print(lam)

lst = [(1,2),(3,1),(5,-2)]

lst.sort(key=lambda k : k[1])
print(lst)

"""sort"""