# -*- coding: utf-8 -*-
"""list_comprehensions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FZtrBG_oRZIRzkH5pJNj_eepydD3ON36
"""

lst = []

for chr in 'Hello':
    lst.append(chr)
print(lst)

lst_comp = [item for item in "hello"]
print(lst_comp)

lst_range = [item for item in range(0,100)]
print(lst_range)
print('---------------')
lst_range = [item*2 for item in range(0,100)]
print(lst_range)
print('---------------')
lst_range = [item*item for item in range(0,100)]
print(lst_range)
print(lst_range.count(100))
print(len(lst_range))
print('---------------')
lst_range = [item*item for item in range(0,100) if item % 2 == 0]
print(lst_range)
print(lst_range.count(100))
print(len(lst_range))

"""to do sets just change to {}
dicts
"""

my_dict = {
    'steve':51,
    'driver':1
}

comp = {key:value**2 for key, value in my_dict.items()}
print(comp)

comp = {num:num*2 for num in [1,2,3]}
print(comp)

name = "S t e p h e n C h e s n o w i t z"
split_name = name.split()
print(split_name)

duplicates = []
for letter in split_name:
    if split_name.count(letter) > 1:
        duplicates.append(letter)
print(duplicates)
print(duplicates.count('t'))

dup = list(set(let for let in split_name if split_name.count(let) > 1))
print(dup)