# -*- coding: utf-8 -*-
"""zip.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kv6gSTx2f9rYvvjqIVaoZSXHsIKdrZiK

zip() combines lists
"""

list_1 = [2,4,6,8,10]
list_2 = [1,3,5,7,9]
tups = ((list(zip(list_2, list_1))))
for tup in tups:
    s = sum(tup)
    print (s)